---@class ShellPool
---Pool of baked blueprint SHELLS used as per-instance spawn roots, so a per-instance edit of a
---NETWORKED object (vehicles) can be previewed live.
---
---Why this exists, in one line: `CreateEntitiesFromBlueprint` will not build a networked entity
---from a runtime clone, and every way of making that clone "known" to the engine crashes the realm
---instead (`docs/vehicle-edit-crash.md`). What DOES work is keeping a baked blueprint as the spawn
---ROOT and letting it reference synthesized data -- measured in `docs/bake-pipeline.md` §10.
---
---So MapEditor claims a shell, points its `object` at the clone it already builds, and spawns the
---instance from the shell. The clone machinery is unchanged; only the spawn root differs.
---
---The pool is optional. Without a baked superbundle (`tools/shells/generate_shells.py`) every entry
---point returns nil and callers fall back to the Disable/Enable refresh -- exactly the behaviour
---before this existed: the edit is still recorded and still bakes correctly, only the live preview
---is missing.
ShellPool = class 'ShellPool'

---@type Logger
local m_Logger = Logger('ShellPool', false)

-- Generated by tools/shells/generate_shells.py. Absent on a checkout that has never baked the pool,
-- which must not break the mod -- hence pcall rather than a bare require.
local s_ManifestOk, m_Manifest = pcall(require, '__shared/ShellManifest')

if not s_ManifestOk or type(m_Manifest) ~= 'table' or m_Manifest.shells == nil then
	m_Manifest = nil
end

---Stable hash of a guid string -> a starting index in the manifest.
local function HashKey(p_Key, p_Count)
	local s_Hash = 5381

	for i = 1, #p_Key do
		-- djb2, kept in a range Lua handles exactly.
		s_Hash = (s_Hash * 33 + p_Key:byte(i)) % 2147483647
	end

	return (s_Hash % p_Count) + 1
end

function ShellPool:__init()
	self:RegisterVars()
	self:RegisterEvents()
end

function ShellPool:RegisterVars()
	---Manifest index -> loaded shell DataContainer. Sparse until the bundle finishes loading.
	self.m_Shells = {}
	---Manifest index -> gameObjectGuid (string) currently holding it.
	self.m_HeldBy = {}
	---gameObjectGuid (string) -> manifest index.
	self.m_IndexOf = {}
	self.m_Mounted = false
	self.m_LoadedCount = 0
end

function ShellPool:RegisterEvents()
	if m_Manifest == nil then
		m_Logger:Write('No shell manifest baked; live preview of networked objects is disabled.')
		return
	end

	Events:Subscribe('Level:LoadResources', self, self.OnLoadResources)

	Events:Subscribe('Level:Destroy', self, self.OnLevelDestroy)
	Hooks:Install('ResourceManager:LoadBundles', 100, self, self.OnLoadBundles)
end

function ShellPool:OnLoadResources()
	-- Shells are per-level resources: everything from the previous level is gone.
	self:RegisterVars()

	local s_Ok, s_Err = pcall(function()
		ResourceManager:MountSuperBundle(m_Manifest.superBundle)
	end)

	if not s_Ok then
		m_Logger:Warning('Could not mount ' .. tostring(m_Manifest.superBundle) .. ' (' ..
			tostring(s_Err) .. '); live preview of networked objects is disabled this level.')
		return
	end

	self.m_Mounted = true

	for l_Index, l_Shell in ipairs(m_Manifest.shells) do
		ResourceManager:RegisterInstanceLoadHandlerOnce(
			Guid(l_Shell.partition), Guid(l_Shell.instance),
			function(p_Instance)
				-- Keyed by MANIFEST INDEX, never by arrival order: the two realms load these
				-- independently and must agree on which shell is which.
				self.m_Shells[l_Index] = _G[p_Instance.typeInfo.name](p_Instance)
				self.m_LoadedCount = self.m_LoadedCount + 1
			end)
	end
end

---Get our bundle loaded alongside the level's. Mounting the superbundle alone is not enough -- the
---bundle inside it has to be in the list the engine loads for this level.
function ShellPool:OnLoadBundles(p_Hook, p_Bundles, p_Compartment)
	if not self.m_Mounted or m_Manifest.bundle == nil then
		return
	end

	local s_LevelName = SharedUtils:GetLevelName()
	local s_HasLevel = false
	local s_HasOurs = false

	for _, l_Bundle in ipairs(p_Bundles) do
		if l_Bundle == s_LevelName then s_HasLevel = true end
		if l_Bundle == m_Manifest.bundle then s_HasOurs = true end
	end

	if not s_HasLevel or s_HasOurs then
		return
	end

	-- PREPEND, preserving anything another mod added on this same event. Replacing the list would
	-- silently drop e.g. Terrain_Tools' decal override.
	local s_New = { m_Manifest.bundle }

	for _, l_Bundle in ipairs(p_Bundles) do
		s_New[#s_New + 1] = l_Bundle
	end

	p_Hook:Pass(s_New, p_Compartment)
end

function ShellPool:OnLevelDestroy()
	self:RegisterVars()
end

--- DISABLED: a baked shell still cannot be spawned as a NETWORKED entity.
---
--- Measured 2026-08-22, in this order:
---   * shell loads (256/256), every blueprint field matched against a real VehicleBlueprint
---     (LAV25) -- entity-bus flags, descriptor, interfaceHasConnections all made to match;
---   * CreateEntitiesFromBlueprint(shell, networked = true) -> nil, no entity bus;
---   * with networked = false it FAULTS exactly as a stock vehicle blueprint does, which says the
---     shell is a well-formed vehicle blueprint rather than malformed data;
---   * adding the shell to the level's blueprintRegistry at load time succeeded (146 -> 147) and
---     then the realm crashed on spawn -- identically to a synthesized clone.
---
--- So a networked spawn needs its blueprint in the LEVEL's blueprint registry, and that registry
--- cannot be mutated at runtime by anything, baked or not. Shells live in their own bundle, which
--- no runtime step can change.
---
--- Leaving this returning false keeps the known-good behaviour: vehicles refresh (Disable/Enable)
--- instead of rebuilding, exactly as before the pool existed. Everything else here -- the bake,
--- the mount, the manifest, the 256 loaded shells -- is verified and kept, because the remaining
---problem is WHERE the shells are baked, not the pool itself. See docs/bake-pipeline.md §10.
local SHELL_PREVIEW_ENABLED = false

---True when a shell could be handed out right now.
function ShellPool:IsReady()
	return SHELL_PREVIEW_ENABLED and m_Manifest ~= nil and self.m_Mounted and self.m_LoadedCount > 0
end

---Pick a shell index for `p_Key` DETERMINISTICALLY.
---
---This must not be a free-list pop. Both realms pump re-instantiation independently
---(`GameObjectManager:OnReinstantiatePump`), so each decides its own shell for the same object --
---and if client and server disagree about which blueprint an entity was built from, a networked
---spawn is inconsistent between them. Deriving the index from the object's guid, over the
---MANIFEST order (identical everywhere, unlike load-callback arrival order), makes both realms
---land on the same shell with no coordination.
---
---Probing is likewise deterministic, so it stays consistent as long as the realms agree on WHICH
---objects are currently edited. If they ever disagree, they were already desynced.
---@return number|nil
function ShellPool:_IndexFor(p_Key)
	local s_Total = #m_Manifest.shells
	local s_Start = HashKey(p_Key, s_Total)

	for i = 0, s_Total - 1 do
		local s_Index = ((s_Start - 1 + i) % s_Total) + 1

		if self.m_Shells[s_Index] ~= nil and self.m_HeldBy[s_Index] == nil then
			return s_Index
		end
	end

	return nil
end

---Claim a shell for an object and point it at that object's clone, in one step.
---
---There is no way to obtain an UNWIRED shell on purpose: spawning a shell whose `object` is nil
---dereferences null and kills the realm (measured). Wiring is therefore part of acquiring.
---
---@param p_GameObjectGuid Guid|string
---@param p_CloneDC DataContainer  the runtime clone MapEditor already built for this instance
---@return DataContainer|nil  the shell to spawn from, or nil to fall back to a refresh
function ShellPool:Acquire(p_GameObjectGuid, p_CloneDC)
	if not SHELL_PREVIEW_ENABLED or m_Manifest == nil or not self.m_Mounted or p_CloneDC == nil then
		return nil
	end

	local s_Clone = _G[p_CloneDC.typeInfo.name](p_CloneDC)
	local s_Object = s_Clone.object

	if s_Object == nil then
		m_Logger:Warning('Clone for ' .. tostring(p_GameObjectGuid) .. ' has no object; ' ..
			'refusing to wire a shell to nothing.')
		return nil
	end

	local s_Key = tostring(p_GameObjectGuid)
	local s_Index = self.m_IndexOf[s_Key]

	if s_Index == nil then
		s_Index = self:_IndexFor(s_Key)

		if s_Index == nil then
			m_Logger:Warning('No shell available for ' .. s_Key .. ' (' ..
				tostring(self.m_LoadedCount) .. ' loaded). Falling back to refresh; the edit is ' ..
				'still recorded and still bakes correctly.')
			return nil
		end

		self.m_IndexOf[s_Key] = s_Index
		self.m_HeldBy[s_Index] = s_Key
	end

	local s_Shell = self.m_Shells[s_Index]

	if s_Shell == nil then
		self:Release(p_GameObjectGuid)
		return nil
	end

	local s_Ok, s_Err = pcall(function()
		s_Shell:MakeWritable()
		s_Shell.object = s_Object
	end)

	if not s_Ok then
		m_Logger:Error('Could not wire shell ' .. tostring(s_Index) .. ' for ' .. s_Key .. ': ' ..
			tostring(s_Err))
		self:Release(p_GameObjectGuid)
		return nil
	end

	m_Logger:Write('Shell ' .. tostring(s_Index) .. ' wired for ' .. s_Key ..
		' -> live preview via a baked spawn root')

	return s_Shell
end

---Return an object's shell to the pool. Safe to call for objects that never had one.
---
---The shell keeps its last `object` wired rather than being reset to nil: a stale reference is
---inert, while a nil one turns any later spawn into a crash.
---@param p_GameObjectGuid Guid|string
function ShellPool:Release(p_GameObjectGuid)
	local s_Key = tostring(p_GameObjectGuid)
	local s_Index = self.m_IndexOf[s_Key]

	if s_Index == nil then
		return
	end

	self.m_IndexOf[s_Key] = nil
	self.m_HeldBy[s_Index] = nil
end

---@return string  one line for the editor log / diagnostics
function ShellPool:GetStatus()
	if m_Manifest == nil then
		return 'shell pool: not baked (live preview disabled)'
	end

	local s_InUse = 0

	for _ in pairs(self.m_IndexOf) do
		s_InUse = s_InUse + 1
	end

	return 'shell pool: ' .. tostring(self.m_LoadedCount) .. '/' .. tostring(#m_Manifest.shells) ..
		' loaded, ' .. tostring(s_InUse) .. ' in use' .. (self.m_Mounted and '' or ' (NOT mounted)')
end

ShellPool = ShellPool()
