/** Declaration file generated by dts-gen */
/// <reference types="node" />
declare module 'flattree' {
	export class Node {

		public id: string;
		public parent: Node;
		public children: Node[];
		public state: INodeState;

		constructor(node: Node);

		public contains(node: Node): boolean;

		public getChildAt(index: number): Node;

		public getChildren(): Node;

		public getFirstChild(): Node;

		public getLastChild(): Node;

		public getNextSibling(): Node;

		public getParent(): Node;

		public getPreviousSibling(): Node;

		public hasChildren(): boolean;

		public isLastChild(): boolean;

	}
	export interface INodeState {
		depth: number;
		open: boolean;
		path: string;
		prefixMask: string;
		total: number;
		filtered: boolean;
	}
}
