name: Lint

on: [push, pull_request]

jobs:
  changes:
    name: Check Changes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            ui:
              - 'WebUI/**'
    outputs:
      ui: ${{ steps.filter.outputs.ui }}

  lint_ui:
    needs: changes
    if: ${{ needs.changes.outputs.ui == 'true' }}
    name: Lint WebUI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Setup Node 16.x
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Install dependencies
        working-directory: './WebUI'
        run: yarn install
      - name: Build
        working-directory: './WebUI'
        run: |
          yarn build
